<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>Microsoft.SemanticKernel.Connectors.DeepSeek</AssemblyName>
    <RootNamespace>$(AssemblyName)</RootNamespace>
    <TargetFrameworks>net8.0;netstandard2.0</TargetFrameworks>
    <NoWarn>$(NoWarn);NU5104;SKEXP0001,SKEXP0010</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(IsReleaseCandidate)' == 'true'">
    <VersionSuffix>rc</VersionSuffix>
  </PropertyGroup>

  <Import Project="$(RepoRoot)/dotnet/nuget/nuget-package.props" />
  <Import Project="$(RepoRoot)/dotnet/src/InternalUtilities/src/InternalUtilities.props" />

  <PropertyGroup>
    <Title>Semantic Kernel - DeepSeek connector</Title>
    <Description>Semantic Kernel connectors for DeepSeek. Contains clients for chat completion with reasoning content support.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\SemanticKernel.Core\SemanticKernel.Core.csproj" />
  </ItemGroup>

</Project>